DEBUG = False
LOGGING_LEVEL = 'INFO'

HOST = '0.0.0.0'
PORT = 5000

QY_ZONE_ID = ''
QY_ACCESS_KEY_ID = ''
QY_SECRET_ACCESS_KEY = ''

TASK_STARTING_STATUS = 'TASK_RUNNING'
TASK_STOPPING_STATUSES = ('TASK_FINISHED', 'TASK_FAILED', 'TASK_KILLED', 'TASK_LOST')

HANDLER_STARTING_TIMEOUT = 5
HANDLER_STARTING_THRESHOLD = 3
HANDLER_STOP_MERCY = 10
